"""Small renderers that turn scan results into readable review artifacts."""

import html
import json
from typing import Any


def render_json(result: dict[str, Any]) -> str:
    return json.dumps(result, indent=2, sort_keys=True) + "\n"


def render_markdown(result: dict[str, Any]) -> str:
    lines = [
        f"# BoundaryCheck report: {result['service']}", "",
        f"**Customer:** {result['customer']}  ",
        f"**Environment:** {result['environment']}  ",
        f"**Decision:** {result['status']}  ",
        f"**Readiness score:** {result['score']}/100  ",
        f"**Findings:** {result['finding_count']}", "",
    ]
    if result["findings"]:
        for item in result["findings"]:
            lines.extend([
                f"## {item['severity']} · {item['code']} · {item['title']}", "",
                f"- **Where:** `{item['path']}`", f"- **Observed:** `{item['evidence']}`",
                f"- **Why it matters:** {item['explanation']}",
                f"- **Suggested fix:** {item['recommendation']}", "",
            ])
    else:
        lines.extend(["No configured rule found a gap in this profile.", ""])
    lines.extend([f"> {result['disclaimer']}", ""])
    return "\n".join(lines)


def render_html(result: dict[str, Any]) -> str:
    colors = {"CRITICAL": "#b42335", "HIGH": "#ca5c16", "MEDIUM": "#8760c4", "LOW": "#287ca2", "INFO": "#39825b"}
    cards = []
    for item in result["findings"]:
        color = colors[item["severity"]]
        fields = [
            ("Where", item["path"]), ("Observed", item["evidence"]),
            ("Why it matters", item["explanation"]), ("Suggested fix", item["recommendation"]),
        ]
        body = "".join(f"<p><b>{html.escape(label)}:</b> {html.escape(str(value))}</p>" for label, value in fields)
        cards.append(f'<article class="finding" style="--accent:{color}"><span class="tag">{html.escape(item["severity"])}</span><h2>{html.escape(item["code"])} · {html.escape(item["title"])}</h2>{body}</article>')
    empty = '<p class="empty">No configured rule found a gap in this profile.</p>' if not cards else ""
    return f'''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BoundaryCheck · {html.escape(str(result['service']))}</title>
<style>
:root{{color-scheme:light;--ink:#183247;--muted:#567084;--paper:#f5f8fc;--purple:#7654b5;}}
*{{box-sizing:border-box}}body{{margin:0;background:linear-gradient(140deg,#e9f5ff,#f6f0ff 52%,#e9f8f2);font:16px/1.55 system-ui,-apple-system,sans-serif;color:var(--ink)}}
main{{max-width:960px;margin:32px auto;padding:0 20px 48px}}header{{background:#173d55;color:white;border-radius:22px;padding:28px 32px;box-shadow:0 16px 44px #173d5525}}header p{{color:#d1e2ed;margin:.3rem 0}}h1{{margin:0;font-size:2.2rem}}.pill{{display:inline-block;background:#ffffff20;border:1px solid #ffffff4d;border-radius:999px;padding:5px 12px;margin-top:10px;font-weight:700}}
.stats{{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0}}.stat{{background:white;border-radius:14px;padding:12px 18px;box-shadow:0 6px 20px #1b426211}}.stat b{{display:block;font-size:1.25rem}}.finding{{background:white;border-left:6px solid var(--accent);border-radius:14px;padding:18px 22px;margin:14px 0;box-shadow:0 7px 24px #1b426211}}.finding h2{{font-size:1.15rem;margin:.5rem 0}}.finding p{{margin:.42rem 0}}.tag{{color:var(--accent);font-weight:800;font-size:.76rem;letter-spacing:.08em}}.empty{{background:#e7f5e5;padding:20px;border-radius:12px}}footer{{font-size:.9rem;color:var(--muted);margin-top:22px}}
</style><main><header><h1>🛡️ BoundaryCheck</h1><p>{html.escape(str(result['service']))} · {html.escape(str(result['customer']))} · {html.escape(str(result['environment']))}</p><span class="pill">{html.escape(result['status'])}</span></header>
<section class="stats"><div class="stat"><b>{result['score']}/100</b>Readiness score</div><div class="stat"><b>{result['finding_count']}</b>Findings</div><div class="stat"><b>Profile-only</b>Review scope</div></section>
<h2>Review findings</h2>{empty}{''.join(cards)}<footer>{html.escape(result['disclaimer'])}<br>Generated by BoundaryCheck · review each result with the responsible security owner.</footer></main></html>'''
